### ISSUE TITLE
problem: tests broken due to #98

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/emurgolance#101]
problem: tests broken due to #98 

solution: update tests to reflect the new logic documented in #98

**Comment by AshHimself** [comment]
@anbud - sir, i've updated the logic a little bit here to only allow clicking of these buttons during certain situations to avoid the data being changes, as a result i've broken the tests :) 

Assuming we can check the status or something, or do an if statement in the assertions?

**Comment by anbud** [comment]
I'll fix them. :)

**Comment by anbud** [comment]
Fixed in #111.
