### ISSUE TITLE
problem: able to submit same github issue

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/emurgolance#106]
problem: its possible to submit the same github issue multiple times

solution: validate github issue url to not allow duplicates

**Comment by AshHimself** [comment]
Fixed in #108
@emurgobot label "done"
@emurgobot done

**Comment by gsovereignty** [comment]
What happens when you actually want to work on an issue, then you have to wait for something or whatever so you work on another issue, then you want to work on the first issue again?

**Comment by AshHimself** [comment]
Sorry I didn't explain this correctly. You could do this. 

Create Issue for https://github.com/EmurgoHK/emurgolance/issues/106
Pause https://github.com/EmurgoHK/emurgolance/issues/106
Create another issue for https://github.com/EmurgoHK/emurgolance/issues/106
Then start the clock on 106 issue twice.

**Comment by gsovereignty** [comment]
OK, to play devil's advocate, what happens if I press stop on #106 because I think it's done, but then I find after merging that there's more to do?

**Comment by AshHimself** [comment]
You can work on it twice as long as the original timesheet has been completed. e.g. if you merged 106 you would then complete that timecard in Emurgolance. It is possible now to then create another timecard for 106 if for say tests fail or you broke something.

**Comment by gsovereignty** [comment]
Ah ok cool, in that case this is kind of perfect.

You should probably redirect users to the existing issue if they paste it in again.

**Comment by AshHimself** [comment]
There isn't anything to redirect to emurgolance unless we perhaps highlight the issue or something in the queue.

**Comment by gsovereignty** [comment]
Ah yeah, good point. Highlighting it or making it flash for a few seconds is probably a good idea then, just in case people get confused.
