### ISSUE TITLE
problem: payment details are not mandatory in the form

### ISSUE THREAD

**Issue by dilpreetsio** [EmurgoHK/emurgolance#113]
problem: payment details are not mandatory in the form

solution: make the payment details like paypal id etc mandatory

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by gsovereignty** [comment]
I think it's best to let people start working immediately without payment details added. Use a notice bar alert thing to remind them though.

**Comment by dilpreetsio** [comment]
@gazhayes Sounds good I will make the changes to the PR. :)

**Comment by dilpreetsio** [comment]
Done in #114
