### ISSUE TITLE
problem: no notification to user when payment is marked as paid

### ISSUE THREAD

**Issue by dilpreetsio** [EmurgoHK/emurgolance#115]
problem: no notification to user when payment is marked as paid

solution: send a notification to the user when a payment is marked as paid.

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by dilpreetsio** [comment]
Done in #115

**Comment by gsovereignty** [comment]
@emurgobot claim

**Comment by gsovereignty** [comment]
@emurgobot done
