### ISSUE TITLE
Problem: Nonactive timecards can't be edited

### ISSUE THREAD

**Issue by anbud** [EmurgoHK/emurgolance#119]
Problem: Timecards that are not currently active cannot be edited which can be a problem if you want to add/remove time on the timecard after marking it as finished.

Solution: Disable edit and delete button only if payment has already been requested for given timecards.

**Comment by anbud** [comment]
Done in #120.

**Comment by gsovereignty** [comment]
@emurgobot claim

**Comment by gsovereignty** [comment]
@emurgobot label "in progress"

**Comment by gsovereignty** [comment]
@emurgobot claim

**Comment by gsovereignty** [comment]
@emurgobot claim

**Comment by gsovereignty** [comment]
@emurgobot claim
