### ISSUE TITLE
Problem: users unable to update details

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/emurgolance#12]
Problem: There is currently no way for users to update their information such as the the payement details once enetered.

Solution: Implement a settings page where freelancers can add or update personal information.

**Comment by anbud** [comment]
I'll take this one and implement #14 as a part of the settings page. It seems like the simplest solution here.

@emurgobot claim

**Comment by anbud** [comment]
Done in #17. 

@emurgobot label "done"
@emurgobot remove "in progress"
