### ISSUE TITLE
problem: no tests for mod dashboard

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/emurgolance#127]
solution: create tests for mod dashboard, ensure the dashboard is only visible for authenticated users and that the authenticated users role is a moderator.

@anbud *cough*

**Comment by anbud** [comment]
This one's definitely for me.  )

@emurgobot claim

**Comment by AshHimself** [comment]
haha yeh.. tag me in the PR i'd like to see how you do it so I can do future ones.

**Comment by anbud** [comment]
Deal. :)

**Comment by anbud** [comment]
Done in #129.
