### ISSUE TITLE
problem: cannot easily see amounts per project

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#130]
problem: it's not easy for mods to see the total amount spent per project, or the total amount per project per user.

**Comment by samuelralak** [comment]
@emurgobot claim

early bird catches the worm

**Comment by gsovereignty** [comment]
I think you just set a new record

**Comment by samuelralak** [comment]
@emurgobot remove "in progress"
@emurgobot label "done"

**Comment by samuelralak** [comment]
@gazhayes solution doesn't take into account completed/uncompleted timesheets, it just sums up totalEarnings in all timesheets. wasn't sure whether to include that or not
