### ISSUE TITLE
Problem: link to the PR missing from the timesheet

### ISSUE THREAD

**Issue by dilpreetsio** [EmurgoHK/emurgolance#133]
Problem: link to the PR missing from the timesheet. Adding a link to the PR sent by the freelancer will make it easy for the moderator to review the work. 

Solution: Add a field PR to the db & ask the freelancer to add a link while submitting the work.

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by gsovereignty** [comment]
You read my mind!

**Comment by dilpreetsio** [comment]
Completed in #134 
@emurgobot Done

**Comment by geekyd** [comment]
@emurgobot add label 'Done'

**Comment by dilpreetsio** [comment]
@emurgobot label "done"
@emurgobot remove "in progress"
