### ISSUE TITLE
Problem: missing validation for PR 

### ISSUE THREAD

**Issue by dilpreetsio** [EmurgoHK/emurgolance#135]
Problem: missing validation for PR. This issue is a follow up of #133.

Solution: Add validation for PR using github API.

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Just make sure to allow '-' or something if there's no PR for the timesheet. (e.g. Devops work doesn't always need a PR)

**Comment by dilpreetsio** [comment]
Done in #136 
@emurgobot label "done"
@emurgobot remove "in progress"
