### ISSUE TITLE
Problem: Freelancers unable to track earnings

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/emurgolance#14]
Problem: Emurgolance only tracks time and there's currently no way for freelancers to specify rates and track their cumulative earnings.

Potential solution: Allow freelancer to set a rate and have the client confirm or approve it.

ping @anbud @gazhayes

**Comment by gsovereignty** [comment]
> Allow freelancer to set a rate and have the client confirm or approve it.

Sounds good to me

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #17. 

@emurgobot label "done"
