### ISSUE TITLE
Problem: emurgolance does not automatically add project name

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#15]
Problem: emurgolance does not automatically add the project name to the created object. 

Solution: use the github URL to get the project name and add this to the object so that it can be used throughout the app to produce totals for each project etc.

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by dilpreetsio** [comment]
Done in #16

@emurgobot label "done"
@emurgobot remove "in progress"
