### ISSUE TITLE
Problem : user can not login from mobile

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgolance#154]
Problem : user can not login from mobile, it redirects to github and it doesn't work but it works on laptop ( responsive view)

Is this just me or everyone face this ?

**Comment by MadanBhandari** [comment]
On production : User can only login with GitHub, we are gonna keep this or github will be just an alternative ?

ping @gazhayes

**Comment by anbud** [comment]
I can't see the logout button on mobile, so I can't test it. But I believe the GitHub login worked before since I'm logged in already.
![button](https://i.imgur.com/QIJJ4SB.jpg)

**Comment by samuelralak** [comment]
@MadanBhandari logging in works fine for me on mobile

**Comment by MadanBhandari** [comment]
Okay, then first I am working on #158

**Comment by MadanBhandari** [comment]
![whatsapp image 2018-09-22 at 12 09 25 am](https://user-images.githubusercontent.com/6429311/45899947-e454be00-bdfb-11e8-8756-8541e691c4e7.jpeg)

I always get this error, is this happening only with me ?

**Comment by anbud** [comment]
I don't even get to that screen, oauth flow completes automatically when I click on the sign in button.

**Comment by MadanBhandari** [comment]
Now, I am more interested in this problem, why just me ?

I'll check with my friend's mobiles too, may be problem is with my mobile or browser or something specific.

**Comment by anbud** [comment]
It could be. What Android version and Chrome version are you using?

I'm on Galaxy S8, Android 8.0, Chrome 69.

**Comment by MadanBhandari** [comment]
I'm on Oneplus 5T, Android 8.1.0, Chrome 69

**Comment by MadanBhandari** [comment]
I had Fasthub (GitHub client) installed on my mobile, when I uninstalled that, It's working perfectly fine.

Closing this as this problem is not with emurgolance itself.
