### ISSUE TITLE
Problem : Landing page doesn't exist

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgolance#160]
Problem : Landing page doesn't exist, so not logged-in user can't know anything about this project.
Solution : Add Landing page with information about project

Questions : 

1. Who are our targeted audience ?
2. Is this only for internal use at Emurgo or will be available for all users [other than emurgo] ?

ping @gazhayes @anbud

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"
@emurgobot claim

**Comment by gsovereignty** [comment]
It's only for internal use so something simple is ok

**Comment by MadanBhandari** [comment]
Okay, then I'll just make some simple with one background image, icon & login with GitHub button.

If user is logged-in and in development environment, current home page otherwise new landing page.

**Comment by MadanBhandari** [comment]
Done in #161 
@emurgobot done
