### ISSUE TITLE
Problem : On click remove timeline icon, timeline removed without confirmation

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgolance#162]
Problem : Once user clicked on remove timeline icon, timeline removed without confirmation

Eg. When user click once on remove timeline option (or even by mistake), timeline automatically removes

![remove-time](https://user-images.githubusercontent.com/6429311/45899698-32b58d00-bdfb-11e8-86aa-cf4534207171.png)

Solution : 

1. Remove timeline only if user click on OK (or confirm)
2. Add cancel button on confirmation popup and clicking outside of popup box, request should be cancelled

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Yeah, sweet alert api has changed in version 2. Adding showCancelButton should do the trick. 

Since this one is not working correctly, check out other buttons with confirmation dialogs as well, maybe they aren't working as expected as well. :)

**Comment by MadanBhandari** [comment]
Yes, I am looking into this, funny thing is I found this problem on production :D

**Comment by MadanBhandari** [comment]
Fixed in #163 
@emurgobot done
