### ISSUE TITLE
Problem : Hidden modals are not clear what they are

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgolance#164]
Problem : Hidden modals are not clear what they are

Solution : I am not sure myself what they are, add appropriate content (Help Text)

**Comment by MadanBhandari** [comment]
@emurgobot label "UI-UX"

**Comment by anbud** [comment]
Are you thinking about the `Reset hidden modals` button on the settings page?

It just resets all confirmation dialogs to initial state, so they'll all show again. For example, you can click on `hide permanently` button on some confirmation dialogs and they won't be shown again unless you reset hidden modal status with that button.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Done in #167 
@emurgobot done
