### ISSUE TITLE
problem: you are able to have multiple payment types

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/emurgolance#177]
problem: you are able to have multiple payment types

solution: add ability to have a default/primary payment type as apposed to deleting old payment types which may be used in the future.

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
I found out this is not entirely possibly but made it more obvious to the user what payment type is currently their default payment method which moderators will use.

**Comment by samuelralak** [comment]
Default payment type is attached to payment document upon payment request

**Comment by AshHimself** [comment]
Yep @samuelralak I figured this out after doing it again myself :( but then I realised i would at least add in the label to actually let the user know this is the default as you can still save multiple.

**Comment by AshHimself** [comment]
Fixed in #180
@emurgobot label "done"
@emurgobot done
