### ISSUE TITLE
problem: freelancers must check every repository for new issues

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#182]
problem: freelancers must check every repository for new issues

solution: use github API to get all open issues (from all emurgo repos) that are not labeled as in progress and put these on a single page. Use cron job to check for new repositories in the organization and add those automatically.

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by dilpreetsio** [comment]
@gazhayes @anbud  Should we store the issues in the DB or simply display the issues to the user?

Also we do not really need a cron job if we use the second approach

**Comment by gsovereignty** [comment]
Actually yeah the second approach is simpler, you should probably do that

**Comment by dilpreetsio** [comment]
Done in #183 
@emurgobot done
