### ISSUE TITLE
problem: total pending payments not shown

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#188]
problem: when moderators view the details for a freelancer, the total paid earnings (green) are shown, but not the total pending earnings.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
Looks like it's working for me on local

path : `/moderator/user/___userID____`

![user-info-emergolance](https://user-images.githubusercontent.com/6429311/46398156-f7c42b00-c711-11e8-91c0-a1274510596c.png)

ping @gazhayes @samuelralak

**Comment by gsovereignty** [comment]
I should probably have stated this one a bit better:

see the "paid, pending, rejected" items in the list? What's needed is the totals for each of these categories.

**Comment by MadanBhandari** [comment]
>  What's needed is the totals for each of these categories.

You meant by Pending, Rejected, Paid and Total earnings. I got it. I'll update that.

**Comment by MadanBhandari** [comment]
@gazhayes  You meant by like this ?

![updates-payment](https://user-images.githubusercontent.com/6429311/46400255-956e2900-c717-11e8-9683-908ea37d422d.png)

**Comment by gsovereignty** [comment]
Yeah that's perfect

**Comment by MadanBhandari** [comment]
I'll send PR with some UI-UX updates, as well.

**Comment by MadanBhandari** [comment]
Done in #189 
@emurgobot done
