### ISSUE TITLE
problem: fetching PRs with Github API not working

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#190]
problem: [http://emurgolance.org/moderator/repos] fetching PRs with Github API not working. There are some useful errors in the console.

I've used this in the node rebuild script and it should be accessible to node as an env variable.
```
export GITHUB_API_TOKEN='_secret_token_'
```

I'd like to put the production rebuild scripts on github at some point anyway, so maybe it's better to get the token from mongo instead?

**Comment by anbud** [comment]
I know what's going on, it should be called from the server as client code doesn't have access to `process.env`. Sure, we can use a token from Mongo, it will also work and maybe it's better.

@emurgobot claim

**Comment by anbud** [comment]
Done in #192.

Add the token to the mongo database with:
```
db.tokens.insert({
	"_id": "github-api-token",
	"token": "_secret_token_"
})
```

@emurgobot done
