### ISSUE TITLE
redirect to various routes

### ISSUE THREAD

**Issue by cloud-dev0102** [EmurgoHK/emurgolance#201]
I can't redirect to various routes.
This has the routes "/", "/issues","/requestpayment", etc.
But they don't go to real page.

**Comment by anbud** [comment]
Hmm, all of them require that you're signed in, otherwise they'll redirect to the login page I believe. Are you signed in? :)

**Comment by cloud-dev0102** [comment]
It is not reasonable.
What is the most reasonable is to display modal for login.

**Comment by MadanBhandari** [comment]
There is no point to add modal for each page, just redirect them to login, and for not logged-in we have nothing to show and this project is built only for internal use.

**Comment by cloud-dev0102** [comment]
Hi, all?
Have you seen the first page?
It has input field "github issue link".
And when clicking any item, browser url is changed, but page is not.
This is just bug.
So, I propose the following:
1. Don't change browser route when clicking any item.
2. When it is, if user didn't login, let effect to click login item occur.
Regards.

**Comment by anbud** [comment]
Wait, if you're seeing the form with the 'github issue link' input field, you have to be logged in. Users that aren't logged in only see the landing page if I'm not mistaken.

Are you getting any errors in the console or something when you click on the links? I can't reproduce any of this, everything is working properly for me, both locally and in production. :)

**Comment by cloud-dev0102** [comment]
OK, Are you working in this part? In fact, I am a developer invited from freelancer.com by Blockrazor, and want to work with you.
I specialize in node.js frameworks and meteor, react/redux, angular etc.
And I have full experiences to accomplish special techs such as MFA, SSO, Social login, web socket and webRTC and so on.

So, I am looking for new issues from this project, can you help me?
