### ISSUE TITLE
Problem: project stats include rejected payments and does not show manual payments

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/emurgolance#214]
I'm not sure how manual payments should show up (or even if they should at all), or if they should show up in a project.
Solution: fix the way we calculate project-wide stats excluding rejected payments and displaying manual payments

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #220.
Manual payments shouldn't be included in this list as they're not really related to existing EmurgoHK projects I believe.
@emurgobot done
