### ISSUE TITLE
Problem: you can continue work on multiple issues at the same time

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/emurgolance#215]
This is inconsistent with starting work on multiple issues.
Solution1: disable the start button if there is another issue started
Solution2: upon clicking the continue button we should stop the other issue and continue the clicked one. In this case, we need to update the start logic as well.

**Comment by anbud** [comment]
If another issue is currently active, disabling the start button should be sufficient I believe. :)

**Comment by porcellus** [comment]
@emurgobot claim

**Comment by porcellus** [comment]
@emurgobot done in #224
