### ISSUE TITLE
Problem: freelancers can't view manual payments requests on paid requests

### ISSUE THREAD

**Issue by porcellus** [EmurgoHK/emurgolance#219]
Solution: enable manual payments listings on paid requests and display their status.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #226.

@emurgobot done

**Comment by porcellus** [comment]
I don't think this is complete: there is still no display of status and rejection reason

**Comment by anbud** [comment]
Hey, sorry, I missed the part about the status. Shall be fixed. :)

@emurgobot claim
@emurgobot remove "done"

**Comment by anbud** [comment]
Done in #231.

@emurgobot done
