### ISSUE TITLE
problem: not enough comments in the codebase

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#223]
problem: not enough comments in the codebase and much of the time it's not clear what's happening

solution: 
when making change or writing new code please explain what you are doing with very clear comments, ideally there should be comments every 2-3 lines for any pull request from now on. This goes for all repositories (emurgo repositories and blockrazor).

Once you see this please acknowledge :)

**Comment by anbud** [comment]
Acknowledged. :)

**Comment by samuelralak** [comment]
I acknowledge 👍

**Comment by MadanBhandari** [comment]
Acknowledged :100:

**Comment by porcellus** [comment]
Ok

**Comment by omar20261** [comment]
ok
