### ISSUE TITLE
Problem : emurgolance.org is not secure

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgolance#233]
Problem : emurgolance.org is not secure

Solution : Enable https, use letsencrypt or other SSL Certificates

ping @gazhayes

**Comment by gsovereignty** [comment]
I've deployed SSL on the load balancer, this should now be solved but @MadanBhandari to confirm.

**Comment by MadanBhandari** [comment]
Yes, this is now solved :)
