### ISSUE TITLE
Problem: sign in button in the header is not functional

### ISSUE THREAD

**Issue by dilpreetsio** [EmurgoHK/emurgolance#24]
Problem: sign in button in the header is not functional

Solution: Add functionality to the buttons in header

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by gsovereignty** [comment]
We only need to allow sign up/in with github

**Comment by dilpreetsio** [comment]
@gazhayes Yes, I have done the same :)

Done in #25 

@emurgobot label "done"
@emurgobot remove "in progress"

**Comment by samuelralak** [comment]
was actually working on this. I believe I have an issue thats very much
related to this one

**Comment by dilpreetsio** [comment]
@samuelralak I'm really sorry I did not realise that. My bad.

**Comment by samuelralak** [comment]
it’s alright chief, no biggie. don’t worry about it.
