### ISSUE TITLE
Problem : Finishing issue doesn't exclude paused timing

### ISSUE THREAD

**Issue by MadanBhandari** [EmurgoHK/emurgolance#245]
Problem : Finishing issue doesn't exclude paused timing [I found this on production]

ping @gazhayes

**Comment by gsovereignty** [comment]
Can you explain that a bit more? I'm not sure if I understand.

**Comment by MadanBhandari** [comment]
@gazhayes  Steps to reproduce 
1. Start working on issue by entering url of issue
2. Pause for sometime
3. Finish issue by entering url of PR [when it's still on pause]

_PS : It works as expected, if issue is not paused._ 

I usually pause the issue till PR gets merged.

**Comment by gsovereignty** [comment]
Ohhhh, yeah I get it now.

Do you have any ideas about a solution?

**Comment by MadanBhandari** [comment]
I believe If we pick the logged time, instead of current time on while finishing issue, this should fix this.

Actually I am in middle of another issue on cardanoupdate, will look into this after this.

**Comment by porcellus** [comment]
I was just about to comment that. timesheet/methods.js:270 -ish.

**Comment by MadanBhandari** [comment]
@emurgobot claim

**Comment by MadanBhandari** [comment]
@emurgobot done in #247
