### ISSUE TITLE
Problem: user's unable to specify payment milestone

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/emurgolance#35]
Problem: a payment milestone is the total cumulative amount the freelancer should earn before he/she can request for payment - this is currently not tracked or recorded. freelancers should be allowed to specify a payment milestone and request for payment once that milestone is reached.

Solution: Track payment milestone in user settings

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #45
@emurgobot label "done"
@emurgobot done
