### ISSUE TITLE
Problem: user's unable to request for payment

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/emurgolance#36]
Problem: Freelancer's cannot request payment for work done.

Potential Solution: have a pay out button that users can click when a payment milestone is reached or when they need to get paid

**Comment by gsovereignty** [comment]
It's probably better to allow freelancers to set a minimum amount for payouts (e.g there's often overhead and it can be different for each payment type depending on the freelancer's location).

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@gazhayes - to confirm, set a min payout or something then when reached perhaps another process is kicked off? 
Min payout? maybe $200USD or something?

**Comment by gsovereignty** [comment]
From my side, I kind of want to limit the payments to like once a week.

In addition, it's probably best that I set the overhead on my side (deducted from freelancer's payment) and the freelancer is responsible for working out the overhead on their side. Then they can set a minimum and maximum payment amount (some balance between the overhead and "I need money now")  and then it can be processed in one of the weekly batches accordingly.

**Comment by gsovereignty** [comment]
Just let me know if that makes sense or not lol

**Comment by samuelralak** [comment]
@AshHimself @gazhayes #35 is very much related. @AshHimself you could claim that as well

> It's probably better to allow freelancers to set a minimum amount for payouts (e.g there's often overhead and it can be different for each payment type depending on the freelancer's location).

**Comment by AshHimself** [comment]
cheers mate! i'll grab it so we don't get any conflicts!

**Comment by AshHimself** [comment]
@gazhayes - it does make sense mate, but don't worry the C4 will sort it if I get it wrong ;)

**Comment by AshHimself** [comment]
@gazhayes - guessing you can only request payments to a timesheet if you have marked it as finished.. well that's what I did but just putting this here so you can clarify.. this is a bit of a beast of a PR but lots has been done :D

**Comment by AshHimself** [comment]
Fixed in #45 
@emurgobot label "done"
@emurgobot done

@gazhayes - Surely some work will be needed to perfect this process but this is a good start. The Payment page for sure needs to have some filters and search etc.
