### ISSUE TITLE
problem: no tests exist for the payment request process

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/emurgolance#44]
solution: create tests

**Comment by anbud** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
@anbud - if you see any ways I can improve this process (not related for tests) go for it! Happy to improve myself at the same time :)

**Comment by anbud** [comment]
@AshHimself, as far as I can see, everything seems fine in the process. :)
Tests should be done in #49.

@emurgobot label "done"
@emurgobot remove "in progress"
