### ISSUE TITLE
Problem: freelancer's details are not tracked

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#5]
Problem: freelancer's details are not tracked.

Solution: required details are:

Name, github username, payment method (Paypal, SWIFT bank transfer, Bitcoin, Cardano).

**Comment by samuelralak** [comment]
Should these details be required before user starts tracking time?

**Comment by gsovereignty** [comment]
> Should these details be required before user starts tracking time?

Yeah, so I guess maybe part of the signup process.

**Comment by samuelralak** [comment]
We can leave out the name as part of the signup process, let the user enter an email instead, preferably Gmail.

Alternatively, we could enable github sign in and have user enter payment details as an after sign up process. Makes sign up fast and we would also not have to do an additional verification process.

**Comment by gsovereignty** [comment]
Ah duh.... Why didn't I think of this before. We should use Github sign in since everyone needs github anyway.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Done in #9.

@emurgobot label "done"
@emurgobot remove "in progress"
