### ISSUE TITLE
problem: minimum payout is too low

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#62]
problem: 
<img width="356" alt="screen shot 2018-07-27 at 7 21 35 pm" src="https://user-images.githubusercontent.com/8143945/43318272-a9b5705a-91d2-11e8-8441-9b592520deee.png">

Solution: allow the minimum payout to be anything from 0 to 5000

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by dilpreetsio** [comment]
Fixed in #64 
@emurgobot label "done"
@emurgobot done
