### ISSUE TITLE
problem: emurgolance not used in production

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#67]
problem: emurgolance is not being used in production by freelance developers at Emurgo.

solution: starting August 1st, the following devs please track your hours in Emurgolance (emurgolance.org) instead of using google spreadsheets, and log/fix any issues you face.

@anbud 
@samuelralak 
@AshHimself 

Then in September we can roll it out for all freelancers.

**Comment by anbud** [comment]
Deal, I'll start using it from August.

**Comment by samuelralak** [comment]
roger that

**Comment by samuelralak** [comment]
quick question, what would happen to the already tracked hours in the
timesheets?

**Comment by gsovereignty** [comment]
I'll just add them up manually

**Comment by AshHimself** [comment]
@samuelralak - you can actually add them in manually now if you prefer.
