### ISSUE TITLE
problem: unable to modify timecards

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/emurgolance#69]
solution: add ability to change timecards and have an audit history of doing so? or perhaps add timecards without using the time indicator functionality? This is obviously more of a suggestion as it could happen (like today) where I left the timer on :)

**Comment by anbud** [comment]
Yap, this could also happen if you're using an unstable internet connection.

Saving history of edits per timesheet should be sufficient for now. This history can also include all pauses inbetween. We should probably also let users delete their timesheets if they've accidentally logged something.

@emurgobot claim

**Comment by anbud** [comment]
Done in #69.
