### ISSUE TITLE
problem: its possible to modify timecards with 0.00

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/emurgolance#71]
solution: add validation on timecards edits to ensure a time exists

@anbud 

![image](https://user-images.githubusercontent.com/148682/43684606-c16aec16-98d5-11e8-833e-7eef0d4a452b.png)

**Comment by anbud** [comment]
Oh yeah, I forgot about this case. It shall be fixed.

@emurgobot claim

**Comment by anbud** [comment]
Done in #72.
