### ISSUE TITLE
problem: unable to use emurgolance.org

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/emurgolance#83]
problem: emurgolance.org keeps on perpetually refreshing itself from my end and it doesn't load completely when trying to access in an incognito browser window. Not certain if am the the only one experiencing this.

ping @gazhayes @anbud @AshHimself

**Comment by anbud** [comment]
It refreshed once in the last hour, but it seems to be working properly now, at least for me.

**Comment by samuelralak** [comment]
not really sure whats going on. Just tried it on Firefox and its working fine. This is strange, lol.
