### ISSUE TITLE
Problem: moderator cannot see requested payments

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#86]
Problem: moderator cannot see requested payments

<img width="1652" alt="screen shot 2018-08-30 at 6 33 54 pm" src="https://user-images.githubusercontent.com/8143945/44846576-4dc13100-ac83-11e8-8fee-7ff264eac761.png">

**Comment by dilpreetsio** [comment]
@emurgobot claim

**Comment by dilpreetsio** [comment]
Done in #87
