### ISSUE TITLE
problem: total hours not shown

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#90]
problem: in the moderator payments view the total hours selected is not being updated.

<img width="245" alt="screen shot 2018-09-01 at 8 21 27 pm" src="https://user-images.githubusercontent.com/8143945/44945939-f22ea900-ae24-11e8-8da3-5ed8843f8d54.png">

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
Getting this error when I navigate to the admin's payment page. @anbud have you seen this before?
<img width="848" alt="screen shot 2018-09-01 at 8 52 49 pm" src="https://user-images.githubusercontent.com/4476552/44948587-0e344980-ae29-11e8-9ae3-880115f8e7c5.png">

**Comment by anbud** [comment]
Hey, yeah, I've seen it today, I thought it was just happening locally for me. Remove the userId parameter from paymets publish function in payments/server/publications.js and it'll start working again.

**Comment by samuelralak** [comment]
sweet. thanks

**Comment by dilpreetsio** [comment]
@samuelralak Just make sure that the changes do not reinitiate https://github.com/EmurgoHK/emurgolance/issues/86. :)

**Comment by samuelralak** [comment]
@geekyd cool. will do

**Comment by samuelralak** [comment]
done in #94
