### ISSUE TITLE
problem: have to copy/paste github issue addresses to open them

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#91]
problem: on the moderator view, you have to copy/paste github issue addresses to open them

<img width="474" alt="screen shot 2018-09-01 at 8 27 28 pm" src="https://user-images.githubusercontent.com/8143945/44945974-9ca6cc00-ae25-11e8-93e3-16c0f172e870.png">

solution: make 'em links

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
done in #93

**Comment by samuelralak** [comment]
not yet entirely done

**Comment by samuelralak** [comment]
done in #93
