### ISSUE TITLE
problem: issue input not reset after user clicks "start work"

### ISSUE THREAD

**Issue by samuelralak** [EmurgoHK/emurgolance#99]
problem: The issue input isn't reset when user clicks on start work. user either has to refresh page or delete old value to track a new issue. this is bad user user experience

solution: set the input value to empty when user clicks on start work and issue is successfully tracked

**Comment by AshHimself** [comment]
@emurgobot claim

**Comment by AshHimself** [comment]
Fixed in #102
@emurgobot label "done"
@emurgobot done

**Comment by AshHimself** [comment]
@samuelralak - I can't close this one mate :)

**Comment by samuelralak** [comment]
lol, got it 👍
